### ISSUE TITLE
transliterate error - unexpected argument

### ISSUE THREAD

**Issue by drdhaval2785** [hrishikeshrt/PyCDSL#11]
* Python Interface to Cologne Digital Sanskrit Lexicon (CDSL) version: 0.2.0
* Python version: 3.9.1
* Operating System: Bodhi Linux 6

### Description

I have upgraded my python3 to python3.9 which was residing on my system.
I tried to check entry 177290 in MW in REPL mode.

### What I Did

```
$ cdsl
Cologne Sanskrit Digital Lexicon (CDSL)
---------------------------------------
Install or load a lexicon by typing `use <DICT_ID>` e.g. `use MW`.
Type any keyword to search in the selected lexicon. (help or ? for list of options)
Loaded 4 dictionaries.
(CDSL::None) use MW
(CDSL::MW) show 177290
Traceback (most recent call last):
  File "/home/dhaval/.local/bin/cdsl", line 8, in <module>
    sys.exit(main())
  File "/home/dhaval/.local/lib/python3.9/site-packages/pycdsl/cli.py", line 222, in main
    cdsl.cmdloop()
  File "/home/dhaval/.local/lib/python3.9/site-packages/pycdsl/cli.py", line 210, in cmdloop
    super(self.__class__, self).cmdloop(intro="")
  File "/usr/local/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/dhaval/.local/lib/python3.9/site-packages/pycdsl/cli.py", line 170, in do_show
    result.transliterate(
TypeError: transliterate() got an unexpected keyword argument 'transliterate_key'
```

**Comment by hrishikeshrt** [comment]
I just noticed this error and have fixed it (9f422f8585b73b5fe6bfb3f91f747181f93fb074).
Thank you for your very active testing and feedback.
